// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGame = "game"

// Game mapped from table <game>
type Game struct {
	ID         int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`          // 主键ID
	UserID     int64      `gorm:"column:user_id;type:bigint;not null" json:"user_id"`                     // 与user表的主键id关联
	Type       int32      `gorm:"column:type;type:tinyint;not null" json:"type"`                          // 游戏类型，0-选择题，1-判断题，2-填空题，3-滑动选择题，4-图钉答案，5-排序题，6-选择题+音频
	Question   *string    `gorm:"column:question;type:varchar(256)" json:"question"`                      // 问题
	Choice     *string    `gorm:"column:choice;type:text" json:"choice"`                                  // 选项，json存储
	Answer     *string    `gorm:"column:answer;type:text" json:"answer"`                                  // 问题，json存储
	CreateTime *time.Time `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time"` // 创建时间
	UpdateTime *time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time"` // 更新时间
}

// TableName Game's table name
func (*Game) TableName() string {
	return TableNameGame
}
